// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBGmd1lHs1ab8_PkjsIF0JG0KPiZZHqy9I',
//     appId: '1:956647304676:web:0bf38b1e1d876a0293abf1',
//     messagingSenderId: '956647304676',
//     projectId: 'handyman-407821',
//     authDomain: 'handyman-407821.firebaseapp.com',
//     databaseURL: 'https://handyman-407821-default-rtdb.firebaseio.com',
//     storageBucket: 'handyman-407821.appspot.com',
//     measurementId: 'G-0WFBDEMJEC',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB-T_vvsRN2QyxUPuwdzZBqlEAfMXxLhMI',
//     appId: '1:956647304676:android:1c038349ad3bbd8193abf1',
//     messagingSenderId: '956647304676',
//     projectId: 'handyman-407821',
//     databaseURL: 'https://handyman-407821-default-rtdb.firebaseio.com',
//     storageBucket: 'handyman-407821.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDudlzyUyd92XcX7TnH2AmKBLtQU48uOW0',
//     appId: '1:956647304676:ios:05589cb21f2d9e4393abf1',
//     messagingSenderId: '956647304676',
//     projectId: 'handyman-407821',
//     databaseURL: 'https://handyman-407821-default-rtdb.firebaseio.com',
//     storageBucket: 'handyman-407821.appspot.com',
//     iosBundleId: 'com.example.ihsApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDudlzyUyd92XcX7TnH2AmKBLtQU48uOW0',
//     appId: '1:956647304676:ios:fa7798293af5865793abf1',
//     messagingSenderId: '956647304676',
//     projectId: 'handyman-407821',
//     databaseURL: 'https://handyman-407821-default-rtdb.firebaseio.com',
//     storageBucket: 'handyman-407821.appspot.com',
//     iosBundleId: 'com.example.ihsApp.RunnerTests',
//   );
// }
