name: ihserver
version: 0.0.1
description: Ivanhoe Handyman Services web server.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  acme_client: ^1.3.0
  args: ^2.4.2
  cron: ^0.5.1
  dcli: ^3.2.3
  dcli_core: ^3.2.3
  dnsolve: ^1.0.0
  email_validator: ^2.1.17
  http_parser: ^4.0.2
  mailer: ^6.0.1
  mime: ^1.0.4
  mime_type: ^1.0.0
  path: ^1.9.0
  settings_yaml: ^7.1.0
  shelf: ^1.4.1
  shelf_letsencrypt:
    hosted: https://onepub.dev/api/jbbxpsdavu/
    version: ^2.0.0
  shelf_multipart: ^1.0.0
  shelf_rate_limiter: ^1.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  simple_mysql_orm: ^4.0.0

dependency_overides:
  x509:
    hosted: https://onepub.dev/api/jbbxpsdavu/
    version: ^0.2.5
  jose:
    hosted: https://onepub.dev/api/jbbxpsdavu/
    version: ^0.3.4

 
dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.25.0

executable:
  ihserver:
